//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ex3
{
    using System;
    using System.Collections.Generic;
    using System.IO;

    public partial class Agent
    {
        public int ID { get; set; }
        public string Title { get; set; }
        public Nullable<int> AgentTypeID { get; set; }
        public string Address { get; set; }
        public Nullable<long> INN { get; set; }
        public Nullable<long> KPP { get; set; }
        public string DirectorName { get; set; }
        public string Phone { get; set; }
        public string Email { get; set; }
        public string Logo { get; set; }
        public Nullable<int> Priority { get; set; }
        public string PhotoFull
        {
            get
            {
                if(this.Logo == null) return null;
                else
                {
                    string namephoto = Directory.GetCurrentDirectory() + "" + Logo;
                    return namephoto;
                }
            }
        }
        public virtual AgentType AgentType { get; set; }
    }
}
